config:
  validation: true
  warningsAsErrors: false

complexity:
  active: true

  CyclomaticComplexMethod:
    ignoreAnnotated:
      - Composable

  LongParameterList:
    functionThreshold: 8
    ignoreAnnotated:
      - Composable

  LongMethod:
    ignoreAnnotated:
      - Composable

naming:
  FunctionNaming:
    ignoreAnnotated:
      - Composable

style:
  UnusedPrivateMember:
    ignoreAnnotated:
      - Preview
      - PreviewLightDark
  MagicNumber:
    ignorePropertyDeclaration: true
    ignoreCompanionObjectPropertyDeclaration: true
    ignoreAnnotation: true
    active: false
  ForbiddenComment:
    allowedPatterns: 'TODO'
  ReturnCount:
    max: 3

